### ISSUE TITLE
Add configurable storage class

### ISSUE THREAD

**Issue by zalmanu** [PressLabs/z3#1]

**Comment by rciorba** [comment]
fixed in 2e559b9ef504db757c09d044ba0e0fd751b54bdf

**Comment by jmohan007** [comment]
Hi,
I am trying to send the files with "STANDARD" storage class instead of STANDARD_IA. I cannot figure out how to send this input to pput vis z3. I tried to set it in /etc/z3_backup/z3.conf, but it does not seem to accept it.
Thanks.

[centos@ip-10-0-33-127 ~]$ sudo z3 --dataset pool/data --snapshot-prefix zfs-auto-snap_hourly backup --compressor=none --storage-class STANDARD --full --dry-run
usage: z3 [-h] [--s3-prefix S3_PREFIX] [--filesystem FILESYSTEM]
          [--snapshot-prefix SNAPSHOT_PREFIX]
          {backup,restore,status} ...
z3: error: unrecognized arguments: --storage-class STANDARD
[centos@ip-10-0-33-127 ~]$ sudo z3 --dataset pool/data --snapshot-prefix zfs-auto-snap_hourly backup --compressor=none --full --dry-run
zfs send -Lce 'pool/data@zfs-auto-snap_hourly-2019-02-01-0001' | pput --quiet --estimated 3891210972576 --meta size=3891210972576 --meta isfull=true z3-backup/pool/data@zfs-auto-snap_hourly-2019-02-01-0001
Successfuly backed up pool/data@zfs-auto-snap_hourly-2019-02-01-0001: 3.54 T.

**Comment by rciorba** [comment]
@jmohan007 the `--storage-class` argument is for pput (which z3 executes to do the actual uploading, once it figures out which snapshots need to be uploaded). I don't think you can pass it from the z3 command line but it should work if you export the  S3_STORAGE_CLASS env variable

**Comment by jmohan007** [comment]
Hi,

Thanks for responding. Yes, it does not work via z3 as expected. However,
it also did not work via /etc/z3backup/z3.conf as I thought it might and
shown in sample files. Setting environment variable did not work either.
Passing the option directly to pput command line works.

I will likely just hard wire the default in pput.py.

Best regards,
Jitendra

**Comment by rciorba** [comment]
@jmohan007 FYI the config is read from:  `/etc/z3_backup/z3.conf`

**Comment by jmohan007** [comment]
Thanks again for answering my questions. Really appreciated.

z3backup was a typo in my email. It is indeed z3_backup on the system.

I did have an occasion to try to restore and discovered something that may
be a limitation or user error on my part.

We take a monthly full backups and daily incremental. Also, zfs maintains 7
latest daily snapshots. I needed to go back ~2 weeks. So none of the needed
snapshots were on the fileserver. All needed to be restored from S3.

First problem: when restoring a full snapshot, the default is to overwrite
the filesystem. Not what I wanted. So, I did a dry run and modified the
commands to receive the full stream to a new fs. That was ok.

Second: the incremental receive failed with "filesystem modified". It was
not. I got around that by using -F and receiving into the new fs.

While all this worked for me, I suspect this was not the intended use
model. When you get a chance, please let me know what I am doing wrong.

BTW, -Lce option used during backup worked well. No new options needed for
restore.

Best regards,
Jitendra
