### ISSUE TITLE
pput should have a --file parameter

### ISSUE THREAD

**Issue by calind** [PressLabs/z3#11]
pput should use a `--file` parameter instead of `--file-descriptor`. It the `--file` is `-` (the default) it should read from stdin. `--file-descriptor` is not so unixy.

**Comment by rciorba** [comment]
pput is not optimal for uploading large files. It was designed for streams.  
That's why the UX choice was to read from stdin, to hint to the user they're using the wrong tool for the job.
The `--file-descriptor` flag exists to permit debugging (allows you to run the tool and still use an ipdb session).

**Comment by rciorba** [comment]
@calind unless you have other thoughts I'll close this
